Java 17 configuration for Android Gradle Plugin
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.16.8-hotspot
# org.gradle.java.home=C:\\Program Files\\Microsoft\\jdk-17.0.16.8-hotspot


# Gradle performance optimizations
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true 