import { ATTENDANCE_PREFIX } from "../../constants";

export const attendanceUrls = {
  FETCH_STUDENT_ATTENDANCE_LIST: ATTENDANCE_PREFIX + "listStudentAttendence",
  FETCH_SINGLE_ATTENDANCE: ATTENDANCE_PREFIX + "singleAttendance",
  CREATE_STUDENT_ATTENDANCE: ATTENDANCE_PREFIX + "createAttendance",
  UPDATE_STUDENT_ATTENDANCE: ATTENDANCE_PREFIX + "updateAttendance",
  CREATE_EMPLOYEE_ATTENDANCE: ATTENDANCE_PREFIX + "createEmployeeAttendence",
  UPDATE_EMPLOYEE_ATTENDANCE: ATTENDANCE_PREFIX + "updateEmployeeAttendance",
  UPDATE_SELF_ATTENDANCE: ATTENDANCE_PREFIX + "employeeSelfAttendance",
  MARK_LECTURE_ATTENDANCE: ATTENDANCE_PREFIX + "markLectureAttendance",
  FETCH_SINGLE_EMPLOYEE_ATTENDANCE: ATTENDANCE_PREFIX + "singleEmployeeAttendance",
  FETCH_SINGLE_EMPLOYEE_MONTHLY_ATTENDANCE: ATTENDANCE_PREFIX + "singleEmployeeMonthlyAttendance", // ✅ NAYA ADD KARO
};
